### ISSUE TITLE
Linux Alt Issue...

### ISSUE THREAD

**Issue by palbakulich** [henrik/bookmarks_bar_keyboard_shortcuts#1]
It appears that changing your code to allow Linux Use hasn't helped...

Both Ctrl+(1-0) and Alt+(1-0) are used as tab swapping shortcuts in Google Chrome
Developers version 5!

I am trying to edit the source to enable the meta key or Shift to allow Linux Users some
usability of this extension...

**Comment by henrik** [comment]
Thanks for letting me know. Didn't actually try on Linux. I'll try to have a look at this.

**Comment by henrik** [comment]
Modifier on Linux is now Meta. Closed by 6eb3249d04c8b3e474473deb91bd377dd9ebfa5c.

This is getting ridiculous :p

**Comment by henrik** [comment]
Paul, please let me know if it works now. Updated: https://chrome.google.com/extensions/detail/omgmmhpgegfcifjmhpenmjpignkegpal

**Comment by whitered** [comment]
It does not work on my Ubuntu... What is meta key? Is it one with windows logo? I've tried every key (shift, ctrl, alt, win-logo) and no one seems to work.
