### ISSUE TITLE
I'd love a configurable modifier

### ISSUE THREAD

**Issue by trevorturk** [henrik/bookmarks_bar_keyboard_shortcuts#3]
I'm so accustomed to using Command+1 in Safari, it would be nice to be able to use the same thing. I'm not sure if Command+1 (etc) is reserved, though... or maybe I'll just get used to it. 

Thanks for this wonderful extension - very nice! ;)

**Comment by henrik** [comment]
Cmd+numbers is taken by tab switching on OS X.

I tried changing the extension to use Cmd, and it half-worked - the bookmark was triggered, but Chrome also changed the active tab. It might be possible to work around that, though, maybe by first checking which tab is active, then changing back to that tab.

Either way, I have considered adding modifier settings. I may look at this some day soon.

Thanks!

**Comment by deleteme** [comment]
For me, Ctrl + # is bound to switch to a particular Space. What about doing something kind of VIM like, where you can type a key, say, "b", then when you type a number, it will execute that bookmark/bookmarklet.

So, instead of Ctrl + 1, I'd type b1. Or maybe (Ctrl + b)1

**Comment by henrik** [comment]
deleteme: Not sure I want to add the complexity of that kind of shortcut, but configurable modifiers (among shift, ctrl, alt, meta) would probably be a good idea at least.
